project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex01.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.qmd

            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

